List  codesar = [
  {"name": "أفغانستان", "dial_code": "+93", "code": "AF"},
  {"name": "جزر آلاند", "dial_code": "+358", "code": "AX"},
  {"name": "ألبانيا", "dial_code": "+355", "code": "AL"},
  {"name": "الجزائر", "dial_code": "+213", "code": "DZ"},
  {"name": "ساموا الأمريكية", "dial_code": "+1684", "code": "AS"},
  {"name": "أندورا", "dial_code": "+376", "code": "AD"},
  {"name": "أنغولا", "dial_code": "+244", "code": "AO"},
  {"name": "أنغيلا", "dial_code": "+1264", "code": "AI"},
  {"name": "أنتاركتيكا", "dial_code": "+672", "code": "AQ"},
  {"name": "أنتيغوا وبربودا", "dial_code": "+1268", "code": "AG"},
  {"name": "الأرجنتين", "dial_code": "+54", "code": "AR"},
  {"name": "أرمينيا", "dial_code": "+374", "code": "AM"},
  {"name": "أروبا", "dial_code": "+297", "code": "AW"},
  {"name": "أستراليا", "dial_code": "+61", "code": "AU"},
  {"name": "النمسا", "dial_code": "+43", "code": "AT"},
  {"name": "أذربيجان", "dial_code": "+994", "code": "AZ"},
  {"name": "جزر البهاما", "dial_code": "+1242", "code": "BS"},
  {"name": "البحرين", "dial_code": "+973", "code": "BH"},
  {"name": "بنغلاديش", "dial_code": "+880", "code": "BD"},
  {"name": "بربادوس", "dial_code": "+1246", "code": "BB"},
  {"name": "بيلاروسيا", "dial_code": "+375", "code": "BY"},
  {"name": "بلجيكا", "dial_code": "+32", "code": "BE"},
  {"name": "بليز", "dial_code": "+501", "code": "BZ"},
  {"name": "بنين", "dial_code": "+229", "code": "BJ"},
  {"name": "برمودا", "dial_code": "+1441", "code": "BM"},
  {"name": "بوتان", "dial_code": "+975", "code": "BT"},
  {
    "name": "بوليفيا ، دولة متعددة القوميات",
    "dial_code": "+591",
    "code": "BO"
  },
  {"name": "البوسنة والهرسك", "dial_code": "+387", "code": "BA"},
  {"name": "بوتسوانا","dial_code": "+267", "code": "BW"},
  {"name": "البرازيل", "dial_code": "+55", "code": "BR"},
  {"name": "إقليم المحيط البريطاني الهندي", "dial_code": "+246", "code": "IO"},
  {"name": "بروناي دار السلام", "dial_code": "+673", "code": "BN"},
  {"name": "بلغاريا", "dial_code": "+359", "code": "BG"},
  {"name": "بوركينا فاسو", "dial_code": "+226", "code": "BF"},
  {"name": "بوروندي", "dial_code": "+257", "code": "BI"},
  {"name": "كمبوديا", "dial_code": "+855", "code": "KH"},
  {"name": "الكاميرون", "dial_code": "+237", "code": "CM"},
  {"name": "كندا", "dial_code": "+1", "code": "CA"},
  {"name": "الرأس الأخضر", "dial_code": "+238", "code": "CV"},
  {"name": "جزر كايمان", "dial_code": "+ 345", "code": "KY"},
  {"name": "جمهورية افريقيا الوسطى", "dial_code": "+236", "code": "CF"},
  {"name": "تشاد", "dial_code": "+235", "code": "TD"},
  {"name": "تشيلي", "dial_code": "+56", "code": "CL"},
  {"name": "الصين", "dial_code": "+86", "code": "CN"},
  {"name": " جزيرة الكريسماس", "dial_code": "+61", "code": "CX"},
  {"name": "جزر كوكوس (كيلينغ)", "dial_code": "+61", "code": "CC"},
  {"name": "كولومبيا", "dial_code": "+57", "code": "CO"},
  {"name": "جزر القمر", "dial_code": "+269", "code": "KM"},
  {"name": "الكونغو", "dial_code": "+242", "code": "CG"},
  {
    "name": "الكونغو ، جمهورية الكونغو الديمقراطية",
    "dial_code": "+243",
    "code": "CD"
  },
  {"name": "جزر كوك", "dial_code": "+682", "code": "CK"},
  {"name": "كوستا ريكا", "dial_code": "+506", "code": "CR"},
  {"name": "ساحل العاج", "dial_code": "+225", "code": "CI"},
  {"name": "كرواتيا", "dial_code": "+385", "code": "HR"},
  {"name": "كوبا", "dial_code": "+53", "code": "CU"},
  {"name": "قبرص", "dial_code": "+357", "code": "CY"},
  {"name": "الجمهورية التشيكية", "dial_code": "+420", "code": "CZ"},
  {"name": "الدنمارك", "dial_code": "+45", "code": "DK"},
  {"name": "جيبوتي", "dial_code": "+253", "code": "DJ"},
  {"name": "دومينيكا", "dial_code": "+1767", "code": "DM"},
  {"name": "جمهورية الدومينيكان", "dial_code": "+1849", "code": "DO"},
  {"name": "الاكوادور", "dial_code": "+593", "code": "EC"},
  {"name": "مصر", "dial_code": "+20", "code": "EG"},
  {"name": "السلفادور", "dial_code": "+503", "code": "SV"},
  {"name": "غينيا الإستوائية", "dial_code": "+240", "code": "GQ"},
  {"name": "إريتريا", "dial_code": "+291", "code": "ER"},
  {"name": "إستونيا", "dial_code": "+372", "code": "EE"},
  {"name": "أثيوبيا", "dial_code": "+251", "code": "ET"},
  {"name": "جزر فوكلاند (مالفيناس)", "dial_code": "+500", "code": "FK"},
  {"name": "جزر فاروس", "dial_code": "+298", "code": "FO"},
  {"name": "فيجي", "dial_code": "+679", "code": "FJ"},
  {"name": "فنلندا", "dial_code": "+358", "code": "FI"},
  {"name": "فرنسا", "dial_code": "+33", "code": "FR"},
  {"name": "غيانا الفرنسية", "dial_code": "+594", "code": "GF"},
  {"name": "بولينيزيا الفرنسية", "dial_code": "+689", "code": "PF"},
  {"name": "الجابون", "dial_code": "+241", "code": "GA"},
  {"name": "غامبيا", "dial_code": "+220", "code": "GM"},
  {"name": "جورجيا", "dial_code": "+995", "code": "GE"},
  {"name": "ألمانيا", "dial_code": "+49", "code": "DE"},
  {"name": "غانا", "dial_code": "+233", "code": "GH"},
  {"name": "جبل طارق", "dial_code": "+350", "code": "GI"},
  {"name": "اليونان", "dial_code": "+30", "code": "GR"},
  {"name": "الأرض الخضراء", "dial_code": "+299", "code": "GL"},
  {"name": "غرينادا", "dial_code": "+1473", "code": "GD"},
  {"name": "جوادلوب", "dial_code": "+590", "code": "GP"},
  {"name": "غوام", "dial_code": "+1671", "code": "GU"},
  {"name": "غواتيمالا", "dial_code": "+502", "code": "GT"},
  {"name": "غيرنسي", "dial_code": "+44", "code": "GG"},
  {"name": "غينيا", "dial_code": "+224", "code": "GN"},
  {"name": "غينيا بيساو", "dial_code": "+245", "code": "GW"},
  {"name": "غيانا", "dial_code": "+595", "code": "GY"},
  {"name": "هايتي", "dial_code": "+509", "code": "HT"},
  {"name": "الكرسي الرسولي (دولة الفاتيكان)", "dial_code": "+379", "code": "VA"},
  {"name": "هندوراس", "dial_code": "+504", "code": "HN"},
  {"name": "هونج كونج", "dial_code": "+852", "code": "HK"},
  {"name": "هنغاريا", "dial_code": "+36", "code": "HU"},
  {"name": "أيسلندا", "dial_code": "+354", "code": "IS"},
  {"name": "الهند", "dial_code": "+91", "code": "IN"},
  {"name": "إندونيسيا", "dial_code": "+62", "code": "ID"},
  {
    "name": "إيران",
    "dial_code": "+98",
    "code": "IR"
  },
  {"name": "العراق", "dial_code": "+964", "code": "IQ"},
  {"name": "أيرلندا", "dial_code": "+353", "code": "IE"},
  {"name": "جزيرة آيل أوف مان", "dial_code": "+44", "code": "IM"},
  {"name": "إسرائيل", "dial_code": "+972", "code": "IL"},
  {"name": "إيطاليا", "dial_code": "+39", "code": "IT"},
  {"name": "جامايكا", "dial_code": "+1876", "code": "JM"},
  {"name": "اليابان", "dial_code": "+81", "code": "JP"},
  {"name": "جيرسي", "dial_code": "+44", "code": "JE"},
  {"name": "الأردن", "dial_code": "+962", "code": "JO"},
  {"name": "كازاخستان", "dial_code": "+77", "code": "KZ"},
  {"name": "كينيا", "dial_code": "+254", "code": "KE"},
  {"name": "كيريباتي", "dial_code": "+686", "code": "KI"},
  {
    "name": "كوريا ، جمهورية كوريا الشعبية الديمقراطية",
    "dial_code": "+850",
    "code": "KP"
  },
  {"name": "كوريا ، جمهورية كوريا الجنوبية", "dial_code": "+82", "code": "KR"},
  {"name": "الكويت", "dial_code": "+965", "code": "KW"},
  {"name": "قيرغيزستان", "dial_code": "+996", "code": "KG"},
  {"name": "لاوس", "dial_code": "+856", "code": "LA"},
  {"name": "لاتفيا", "dial_code": "+371", "code": "LV"},
  {"name": "لبنان", "dial_code": "+961", "code": "LB"},
  {"name": "ليسوتو", "dial_code": "+266", "code": "LS"},
  {"name": "ليبيريا", "dial_code": "+231", "code": "LR"},
  {"name": "الجماهيرية العربية الليبية", "dial_code": "+218", "code": "LY"},
  {"name": "ليختنشتاين", "dial_code": "+423", "code": "LI"},
  {"name": "ليتوانيا", "dial_code": "+370", "code": "LT"},
  {"name": "لوكسمبورغ", "dial_code": "+352", "code": "LU"},
  {"name": "ماكاو", "dial_code": "+853", "code": "MO"},
  {"name": "مقدونيا", "dial_code": "+389", "code": "MK"},
  {"name": "مدغشقر", "dial_code": "+261", "code": "MG"},
  {"name": "ملاوي", "dial_code": "+265", "code": "MW"},
  {"name": "ماليزيا", "dial_code": "+60", "code": "MY"},
  {"name": "جزر المالديف", "dial_code": "+960", "code": "MV"},
  {"name": "مالي", "dial_code": "+223", "code": "ML"},
  {"name": "مالطا", "dial_code": "+356", "code": "MT"},
  {"name": "جزر مارشال", "dial_code": "+692", "code": "MH"},
  {"name": "مارتينيك", "dial_code": "+596", "code": "MQ"},
  {"name": "موريتانيا", "dial_code": "+222", "code": "MR"},
  {"name": "موريشيوس", "dial_code": "+230", "code": "MU"},
  {"name": "مايوت", "dial_code": "+262", "code": "YT"},
  {"name": "المكسيك", "dial_code": "+52", "code": "MX"},
  {
    "name": "ولايات ميكرونيزيا الموحدة",
    "dial_code": "+691",
    "code": "FM"
  },
  {"name": "مولدوفا", "dial_code": "+373", "code": "MD"},
  {"name": "موناكو", "dial_code": "+377", "code": "MC"},
  {"name": "منغوليا", "dial_code": "+976", "code": "MN"},
  {"name": "الجبل الأسود", "dial_code": "+382", "code": "ME"},
  {"name": "مونتسيرات", "dial_code": "+1664", "code": "MS"},
  {"name": "المغرب", "dial_code": "+212", "code": "MA"},
  {"name": "موزمبيق", "dial_code": "+258", "code": "MZ"},
  {"name": "ميانمار", "dial_code": "+95", "code": "MM"},
  {"name": "ناميبيا", "dial_code": "+264", "code": "NA"},
  {"name": "ناورو", "dial_code": "+674", "code": "NR"},
  {"name": "نيبال", "dial_code": "+977", "code": "NP"},
  {"name": "هولندا", "dial_code": "+31", "code": "NL"},
  {"name": "جزر الأنتيل الهولندية", "dial_code": "+599", "code": "AN"},
  {"name": "كاليدونيا الجديدة", "dial_code": "+687", "code": "NC"},
  {"name": "نيوزيلاندا", "dial_code": "+64", "code": "NZ"},
  {"name": "نيكاراغوا", "dial_code": "+505", "code": "NI"},
  {"name": "النيجر", "dial_code": "+227", "code": "NE"},
  {"name": "نيجيريا", "dial_code": "+234", "code": "NG"},
  {"name": "نيوي", "dial_code": "+683", "code": "NU"},
  {"name": "جزيرة نورفولك", "dial_code": "+672", "code": "NF"},
  {"name": "جزر مريانا الشمالية", "dial_code": "+1670", "code": "MP"},
  {"name": "النرويج", "dial_code": "+47", "code": "NO"},
  {"name": "سلطنة عمان", "dial_code": "+968", "code": "OM"},
  {"name": "باكستان", "dial_code": "+92", "code": "PK"},
  {"name": "بالاو", "dial_code": "+680", "code": "PW"},
  {
    "name": "الأراضي الفلسطينية المحتلة",
    "dial_code": "+970",
    "code": "PS"
  },
  {"name": "بنما", "dial_code": "+507", "code": "PA"},
  {"name": "بابوا غينيا الجديدة", "dial_code": "+675", "code": "PG"},
  {"name": "باراغواي", "dial_code": "+595", "code": "PY"},
  {"name": "بيرو", "dial_code": "+51", "code": "PE"},
  {"name": "فيلبيني", "dial_code": "+63", "code": "PH"},
  {"name": "بيتكيرن", "dial_code": "+872", "code": "PN"},
  {"name": "بولندا", "dial_code": "+48", "code": "PL"},
  {"name": "البرتغال", "dial_code": "+351", "code": "PT"},
  {"name": "بورتوريكو", "dial_code": "+1939", "code": "PR"},
  {"name": "قطر", "dial_code": "+974", "code": "QA"},
  {"name": "رومانيا", "dial_code": "+40", "code": "RO"},
  {"name": "روسيا", "dial_code": "+7", "code": "RU"},
  {"name": "رواندا", "dial_code": "+250", "code": "RW"},
  {"name": "جمع شمل", "dial_code": "+262", "code": "RE"},
  {"name": "سانت بارتيليمي", "dial_code": "+590", "code": "BL"},
  {
    "name": "سانت هيلانة وأسنسيون وتريستان دا كونها",
    "dial_code": "+290",
    "code": "SH"
  },
  {"name": "سانت كيتس ونيفيس", "dial_code": "+1869", "code": "KN"},
  {"name": "القديسة لوسيا", "dial_code": "+1758", "code": "LC"},
  {"name": "القديس مارتن", "dial_code": "+590", "code": "MF"},
  {"name": "سانت بيير وميكلون", "dial_code": "+508", "code": "PM"},
  {
    "name": "سانت فنسنت وجزر غرينادين",
    "dial_code": "+1784",
    "code": "VC"
  },
  {"name": "ساموا", "dial_code": "+685", "code": "WS"},
  {"name": "سان مارينو", "dial_code": "+378", "code": "SM"},
  {"name": "ساو تومي وبرينسيبي", "dial_code": "+239", "code": "ST"},
  {"name": "المملكة العربية السعودية", "dial_code": "+966", "code": "SA"},
  {"name": "السنغال", "dial_code": "+221", "code": "SN"},
  {"name": "صربيا", "dial_code": "+381", "code": "RS"},
  {"name": "سيشيل", "dial_code": "+248", "code": "SC"},
  {"name": "سيرا ليون", "dial_code": "+232", "code": "SL"},
  {"name": "سنغافورة", "dial_code": "+65", "code": "SG"},
  {"name": "سلوفاكيا", "dial_code": "+421", "code": "SK"},
  {"name": "سلوفينيا", "dial_code": "+386", "code": "SI"},
  {"name": "جزر سليمان", "dial_code": "+677", "code": "SB"},
  {"name": "الصومال", "dial_code": "+252", "code": "SO"},
  {"name": "جنوب أفريقيا", "dial_code": "+27", "code": "ZA"},
  {"name": "جنوب السودان", "dial_code": "+211", "code": "SS"},
  {
    "name": "جورجيا الجنوبية وجزر ساندويتش الجنوبية",
    "dial_code": "+500",
    "code": "GS"
  },
  {"name": "إسبانيا", "dial_code": "+34", "code": "ES"},
  {"name": "سيريلانكا", "dial_code": "+94", "code": "LK"},
  {"name": "السودان", "dial_code": "+249", "code": "SD"},
  {"name": "سورينام", "dial_code": "+597", "code": "SR"},
  {"name": "سفالبارد وجان ماين", "dial_code": "+47", "code": "SJ"},
  {"name": "سوازيلاند", "dial_code": "+268", "code": "SZ"},
  {"name": "السويد", "dial_code": "+46", "code": "SE"},
  {"name": "سويسرا", "dial_code": "+41", "code": "CH"},
  {"name": "الجمهورية العربية السورية", "dial_code": "+963", "code": "SY"},
  {"name": "تايوان", "dial_code": "+886", "code": "TW"},
  {"name": "طاجيكستان", "dial_code": "+992", "code": "TJ"},
  {
    "name": "تنزانيا ، جمهورية تنزانيا المتحدة",
    "dial_code": "+255",
    "code": "TZ"
  },
  {"name": "تايلاند", "dial_code": "+66", "code": "TH"},
  {"name": "تيمور ليشتي", "dial_code": "+670", "code": "TL"},
  {"name": "توجو", "dial_code": "+228", "code": "TG"},
  {"name": "توكيلاو", "dial_code": "+690", "code": "TK"},
  {"name": "تونغا", "dial_code": "+676", "code": "TO"},
  {"name": "ترينداد وتوباغو", "dial_code": "+1868", "code": "TT"},
  {"name": "تونس", "dial_code": "+216", "code": "TN"},
  {"name": "تركيا", "dial_code": "+90", "code": "TR"},
  {"name": "تركمانستان", "dial_code": "+993", "code": "TM"},
  {"name": "جزر تركس وكايكوس", "dial_code": "+1649", "code": "TC"},
  {"name": "توفالو", "dial_code": "+688", "code": "TV"},
  {"name": "أوغندا", "dial_code": "+256", "code": "UG"},
  {"name": "أوكرانيا", "dial_code": "+380", "code": "UA"},
  {"name": "الإمارات العربية المتحدة", "dial_code": "+971", "code": "AE"},
  {"name": "المملكة المتحدة", "dial_code": "+44", "code": "GB"},
  {"name": "الولايات المتحدة الأمريكية", "dial_code": "+1", "code": "US"},
  {"name": "أوروغواي", "dial_code": "+598", "code": "UY"},
  {"name": "أوزبكستان", "dial_code": "+998", "code": "UZ"},
  {"name": "فانواتو", "dial_code": "+678", "code": "VU"},
  {
    "name": "فنزويلا ، جمهورية فنزويلا البوليفارية",
    "dial_code": "+58",
    "code": "VE"
  },
  {"name": "فيتنام", "dial_code": "+84", "code": "VN"},
  {"name": "جزر العذراء البريطانية", "dial_code": "+1284", "code": "VG"},
  {"name": "جزر فيرجن الأمريكية", "dial_code": "+1340", "code": "VI"},
  {"name": "واليس وفوتونا", "dial_code": "+681", "code": "WF"},
  {"name": "اليمن", "dial_code": "+967", "code": "YE"},
  {"name": "زامبيا", "dial_code": "+260", "code": "ZM"},
  {"name": "زيمبابوي", "dial_code": "+263", "code": "ZW"}
];
List  codesen = [
  {"name": "Afghanistan", "dial_code": "+93", "code": "AF"},
  {"name": "Aland Islands", "dial_code": "+358", "code": "AX"},
  {"name": "Albania", "dial_code": "+355", "code": "AL"},
  {"name": "Algeria", "dial_code": "+213", "code": "DZ"},
  {"name": "AmericanSamoa", "dial_code": "+1684", "code": "AS"},
  {"name": "Andorra", "dial_code": "+376", "code": "AD"},
  {"name": "Angola", "dial_code": "+244", "code": "AO"},
  {"name": "Anguilla", "dial_code": "+1264", "code": "AI"},
  {"name": "Antarctica", "dial_code": "+672", "code": "AQ"},
  {"name": "Antigua and Barbuda", "dial_code": "+1268", "code": "AG"},
  {"name": "Argentina", "dial_code": "+54", "code": "AR"},
  {"name": "Armenia", "dial_code": "+374", "code": "AM"},
  {"name": "Aruba", "dial_code": "+297", "code": "AW"},
  {"name": "Australia", "dial_code": "+61", "code": "AU"},
  {"name": "Austria", "dial_code": "+43", "code": "AT"},
  {"name": "Azerbaijan", "dial_code": "+994", "code": "AZ"},
  {"name": "Bahamas", "dial_code": "+1242", "code": "BS"},
  {"name": "Bahrain", "dial_code": "+973", "code": "BH"},
  {"name": "Bangladesh", "dial_code": "+880", "code": "BD"},
  {"name": "Barbados", "dial_code": "+1246", "code": "BB"},
  {"name": "Belarus", "dial_code": "+375", "code": "BY"},
  {"name": "Belgium", "dial_code": "+32", "code": "BE"},
  {"name": "Belize", "dial_code": "+501", "code": "BZ"},
  {"name": "Benin", "dial_code": "+229", "code": "BJ"},
  {"name": "Bermuda", "dial_code": "+1441", "code": "BM"},
  {"name": "Bhutan", "dial_code": "+975", "code": "BT"},
  {
    "name": "Bolivia, Plurinational State of",
    "dial_code": "+591",
    "code": "BO"
  },
  {"name": "Bosnia and Herzegovina", "dial_code": "+387", "code": "BA"},
  {"name": "Botswana", "dial_code": "+267", "code": "BW"},
  {"name": "Brazil", "dial_code": "+55", "code": "BR"},
  {"name": "British Indian Ocean Territory", "dial_code": "+246", "code": "IO"},
  {"name": "Brunei Darussalam", "dial_code": "+673", "code": "BN"},
  {"name": "Bulgaria", "dial_code": "+359", "code": "BG"},
  {"name": "Burkina Faso", "dial_code": "+226", "code": "BF"},
  {"name": "Burundi", "dial_code": "+257", "code": "BI"},
  {"name": "Cambodia", "dial_code": "+855", "code": "KH"},
  {"name": "Cameroon", "dial_code": "+237", "code": "CM"},
  {"name": "Canada", "dial_code": "+1", "code": "CA"},
  {"name": "Cape Verde", "dial_code": "+238", "code": "CV"},
  {"name": "Cayman Islands", "dial_code": "+ 345", "code": "KY"},
  {"name": "Central African Republic", "dial_code": "+236", "code": "CF"},
  {"name": "Chad", "dial_code": "+235", "code": "TD"},
  {"name": "Chile", "dial_code": "+56", "code": "CL"},
  {"name": "China", "dial_code": "+86", "code": "CN"},
  {"name": "Christmas Island", "dial_code": "+61", "code": "CX"},
  {"name": "Cocos (Keeling) Islands", "dial_code": "+61", "code": "CC"},
  {"name": "Colombia", "dial_code": "+57", "code": "CO"},
  {"name": "Comoros", "dial_code": "+269", "code": "KM"},
  {"name": "Congo", "dial_code": "+242", "code": "CG"},
  {
    "name": "Congo, The Democratic Republic of the Congo",
    "dial_code": "+243",
    "code": "CD"
  },
  {"name": "Cook Islands", "dial_code": "+682", "code": "CK"},
  {"name": "Costa Rica", "dial_code": "+506", "code": "CR"},
  {"name": "Cote d'Ivoire", "dial_code": "+225", "code": "CI"},
  {"name": "Croatia", "dial_code": "+385", "code": "HR"},
  {"name": "Cuba", "dial_code": "+53", "code": "CU"},
  {"name": "Cyprus", "dial_code": "+357", "code": "CY"},
  {"name": "Czech Republic", "dial_code": "+420", "code": "CZ"},
  {"name": "Denmark", "dial_code": "+45", "code": "DK"},
  {"name": "Djibouti", "dial_code": "+253", "code": "DJ"},
  {"name": "Dominica", "dial_code": "+1767", "code": "DM"},
  {"name": "Dominican Republic", "dial_code": "+1849", "code": "DO"},
  {"name": "Ecuador", "dial_code": "+593", "code": "EC"},
  {"name": "Egypt", "dial_code": "+20", "code": "EG"},
  {"name": "El Salvador", "dial_code": "+503", "code": "SV"},
  {"name": "Equatorial Guinea", "dial_code": "+240", "code": "GQ"},
  {"name": "Eritrea", "dial_code": "+291", "code": "ER"},
  {"name": "Estonia", "dial_code": "+372", "code": "EE"},
  {"name": "Ethiopia", "dial_code": "+251", "code": "ET"},
  {"name": "Falkland Islands (Malvinas)", "dial_code": "+500", "code": "FK"},
  {"name": "Faroe Islands", "dial_code": "+298", "code": "FO"},
  {"name": "Fiji", "dial_code": "+679", "code": "FJ"},
  {"name": "Finland", "dial_code": "+358", "code": "FI"},
  {"name": "France", "dial_code": "+33", "code": "FR"},
  {"name": "French Guiana", "dial_code": "+594", "code": "GF"},
  {"name": "French Polynesia", "dial_code": "+689", "code": "PF"},
  {"name": "Gabon", "dial_code": "+241", "code": "GA"},
  {"name": "Gambia", "dial_code": "+220", "code": "GM"},
  {"name": "Georgia", "dial_code": "+995", "code": "GE"},
  {"name": "Germany", "dial_code": "+49", "code": "DE"},
  {"name": "Ghana", "dial_code": "+233", "code": "GH"},
  {"name": "Gibraltar", "dial_code": "+350", "code": "GI"},
  {"name": "Greece", "dial_code": "+30", "code": "GR"},
  {"name": "Greenland", "dial_code": "+299", "code": "GL"},
  {"name": "Grenada", "dial_code": "+1473", "code": "GD"},
  {"name": "Guadeloupe", "dial_code": "+590", "code": "GP"},
  {"name": "Guam", "dial_code": "+1671", "code": "GU"},
  {"name": "Guatemala", "dial_code": "+502", "code": "GT"},
  {"name": "Guernsey", "dial_code": "+44", "code": "GG"},
  {"name": "Guinea", "dial_code": "+224", "code": "GN"},
  {"name": "Guinea-Bissau", "dial_code": "+245", "code": "GW"},
  {"name": "Guyana", "dial_code": "+595", "code": "GY"},
  {"name": "Haiti", "dial_code": "+509", "code": "HT"},
  {"name": "Holy See (Vatican City State)", "dial_code": "+379", "code": "VA"},
  {"name": "Honduras", "dial_code": "+504", "code": "HN"},
  {"name": "Hong Kong", "dial_code": "+852", "code": "HK"},
  {"name": "Hungary", "dial_code": "+36", "code": "HU"},
  {"name": "Iceland", "dial_code": "+354", "code": "IS"},
  {"name": "India", "dial_code": "+91", "code": "IN"},
  {"name": "Indonesia", "dial_code": "+62", "code": "ID"},
  {
    "name": "Iran, Islamic Republic of Persian Gulf",
    "dial_code": "+98",
    "code": "IR"
  },
  {"name": "Iraq", "dial_code": "+964", "code": "IQ"},
  {"name": "Ireland", "dial_code": "+353", "code": "IE"},
  {"name": "Isle of Man", "dial_code": "+44", "code": "IM"},
  {"name": "Israel", "dial_code": "+972", "code": "IL"},
  {"name": "Italy", "dial_code": "+39", "code": "IT"},
  {"name": "Jamaica", "dial_code": "+1876", "code": "JM"},
  {"name": "Japan", "dial_code": "+81", "code": "JP"},
  {"name": "Jersey", "dial_code": "+44", "code": "JE"},
  {"name": "Jordan", "dial_code": "+962", "code": "JO"},
  {"name": "Kazakhstan", "dial_code": "+77", "code": "KZ"},
  {"name": "Kenya", "dial_code": "+254", "code": "KE"},
  {"name": "Kiribati", "dial_code": "+686", "code": "KI"},
  {
    "name": "Korea, Democratic People's Republic of Korea",
    "dial_code": "+850",
    "code": "KP"
  },
  {"name": "Korea, Republic of South Korea", "dial_code": "+82", "code": "KR"},
  {"name": "Kuwait", "dial_code": "+965", "code": "KW"},
  {"name": "Kyrgyzstan", "dial_code": "+996", "code": "KG"},
  {"name": "Laos", "dial_code": "+856", "code": "LA"},
  {"name": "Latvia", "dial_code": "+371", "code": "LV"},
  {"name": "Lebanon", "dial_code": "+961", "code": "LB"},
  {"name": "Lesotho", "dial_code": "+266", "code": "LS"},
  {"name": "Liberia", "dial_code": "+231", "code": "LR"},
  {"name": "Libyan Arab Jamahiriya", "dial_code": "+218", "code": "LY"},
  {"name": "Liechtenstein", "dial_code": "+423", "code": "LI"},
  {"name": "Lithuania", "dial_code": "+370", "code": "LT"},
  {"name": "Luxembourg", "dial_code": "+352", "code": "LU"},
  {"name": "Macao", "dial_code": "+853", "code": "MO"},
  {"name": "Macedonia", "dial_code": "+389", "code": "MK"},
  {"name": "Madagascar", "dial_code": "+261", "code": "MG"},
  {"name": "Malawi", "dial_code": "+265", "code": "MW"},
  {"name": "Malaysia", "dial_code": "+60", "code": "MY"},
  {"name": "Maldives", "dial_code": "+960", "code": "MV"},
  {"name": "Mali", "dial_code": "+223", "code": "ML"},
  {"name": "Malta", "dial_code": "+356", "code": "MT"},
  {"name": "Marshall Islands", "dial_code": "+692", "code": "MH"},
  {"name": "Martinique", "dial_code": "+596", "code": "MQ"},
  {"name": "Mauritania", "dial_code": "+222", "code": "MR"},
  {"name": "Mauritius", "dial_code": "+230", "code": "MU"},
  {"name": "Mayotte", "dial_code": "+262", "code": "YT"},
  {"name": "Mexico", "dial_code": "+52", "code": "MX"},
  {
    "name": "Micronesia, Federated States of Micronesia",
    "dial_code": "+691",
    "code": "FM"
  },
  {"name": "Moldova", "dial_code": "+373", "code": "MD"},
  {"name": "Monaco", "dial_code": "+377", "code": "MC"},
  {"name": "Mongolia", "dial_code": "+976", "code": "MN"},
  {"name": "Montenegro", "dial_code": "+382", "code": "ME"},
  {"name": "Montserrat", "dial_code": "+1664", "code": "MS"},
  {"name": "Morocco", "dial_code": "+212", "code": "MA"},
  {"name": "Mozambique", "dial_code": "+258", "code": "MZ"},
  {"name": "Myanmar", "dial_code": "+95", "code": "MM"},
  {"name": "Namibia", "dial_code": "+264", "code": "NA"},
  {"name": "Nauru", "dial_code": "+674", "code": "NR"},
  {"name": "Nepal", "dial_code": "+977", "code": "NP"},
  {"name": "Netherlands", "dial_code": "+31", "code": "NL"},
  {"name": "Netherlands Antilles", "dial_code": "+599", "code": "AN"},
  {"name": "New Caledonia", "dial_code": "+687", "code": "NC"},
  {"name": "New Zealand", "dial_code": "+64", "code": "NZ"},
  {"name": "Nicaragua", "dial_code": "+505", "code": "NI"},
  {"name": "Niger", "dial_code": "+227", "code": "NE"},
  {"name": "Nigeria", "dial_code": "+234", "code": "NG"},
  {"name": "Niue", "dial_code": "+683", "code": "NU"},
  {"name": "Norfolk Island", "dial_code": "+672", "code": "NF"},
  {"name": "Northern Mariana Islands", "dial_code": "+1670", "code": "MP"},
  {"name": "Norway", "dial_code": "+47", "code": "NO"},
  {"name": "Oman", "dial_code": "+968", "code": "OM"},
  {"name": "Pakistan", "dial_code": "+92", "code": "PK"},
  {"name": "Palau", "dial_code": "+680", "code": "PW"},
  {
    "name": "Palestinian Territory, Occupied",
    "dial_code": "+970",
    "code": "PS"
  },
  {"name": "Panama", "dial_code": "+507", "code": "PA"},
  {"name": "Papua New Guinea", "dial_code": "+675", "code": "PG"},
  {"name": "Paraguay", "dial_code": "+595", "code": "PY"},
  {"name": "Peru", "dial_code": "+51", "code": "PE"},
  {"name": "Philippines", "dial_code": "+63", "code": "PH"},
  {"name": "Pitcairn", "dial_code": "+872", "code": "PN"},
  {"name": "Poland", "dial_code": "+48", "code": "PL"},
  {"name": "Portugal", "dial_code": "+351", "code": "PT"},
  {"name": "Puerto Rico", "dial_code": "+1939", "code": "PR"},
  {"name": "Qatar", "dial_code": "+974", "code": "QA"},
  {"name": "Romania", "dial_code": "+40", "code": "RO"},
  {"name": "Russia", "dial_code": "+7", "code": "RU"},
  {"name": "Rwanda", "dial_code": "+250", "code": "RW"},
  {"name": "Reunion", "dial_code": "+262", "code": "RE"},
  {"name": "Saint Barthelemy", "dial_code": "+590", "code": "BL"},
  {
    "name": "Saint Helena, Ascension and Tristan Da Cunha",
    "dial_code": "+290",
    "code": "SH"
  },
  {"name": "Saint Kitts and Nevis", "dial_code": "+1869", "code": "KN"},
  {"name": "Saint Lucia", "dial_code": "+1758", "code": "LC"},
  {"name": "Saint Martin", "dial_code": "+590", "code": "MF"},
  {"name": "Saint Pierre and Miquelon", "dial_code": "+508", "code": "PM"},
  {
    "name": "Saint Vincent and the Grenadines",
    "dial_code": "+1784",
    "code": "VC"
  },
  {"name": "Samoa", "dial_code": "+685", "code": "WS"},
  {"name": "San Marino", "dial_code": "+378", "code": "SM"},
  {"name": "Sao Tome and Principe", "dial_code": "+239", "code": "ST"},
  {"name": "Saudi Arabia", "dial_code": "+966", "code": "SA"},
  {"name": "Senegal", "dial_code": "+221", "code": "SN"},
  {"name": "Serbia", "dial_code": "+381", "code": "RS"},
  {"name": "Seychelles", "dial_code": "+248", "code": "SC"},
  {"name": "Sierra Leone", "dial_code": "+232", "code": "SL"},
  {"name": "Singapore", "dial_code": "+65", "code": "SG"},
  {"name": "Slovakia", "dial_code": "+421", "code": "SK"},
  {"name": "Slovenia", "dial_code": "+386", "code": "SI"},
  {"name": "Solomon Islands", "dial_code": "+677", "code": "SB"},
  {"name": "Somalia", "dial_code": "+252", "code": "SO"},
  {"name": "South Africa", "dial_code": "+27", "code": "ZA"},
  {"name": "South Sudan", "dial_code": "+211", "code": "SS"},
  {
    "name": "South Georgia and the South Sandwich Islands",
    "dial_code": "+500",
    "code": "GS"
  },
  {"name": "Spain", "dial_code": "+34", "code": "ES"},
  {"name": "Sri Lanka", "dial_code": "+94", "code": "LK"},
  {"name": "Sudan", "dial_code": "+249", "code": "SD"},
  {"name": "Suriname", "dial_code": "+597", "code": "SR"},
  {"name": "Svalbard and Jan Mayen", "dial_code": "+47", "code": "SJ"},
  {"name": "Swaziland", "dial_code": "+268", "code": "SZ"},
  {"name": "Sweden", "dial_code": "+46", "code": "SE"},
  {"name": "Switzerland", "dial_code": "+41", "code": "CH"},
  {"name": "Syrian Arab Republic", "dial_code": "+963", "code": "SY"},
  {"name": "Taiwan", "dial_code": "+886", "code": "TW"},
  {"name": "Tajikistan", "dial_code": "+992", "code": "TJ"},
  {
    "name": "Tanzania, United Republic of Tanzania",
    "dial_code": "+255",
    "code": "TZ"
  },
  {"name": "Thailand", "dial_code": "+66", "code": "TH"},
  {"name": "Timor-Leste", "dial_code": "+670", "code": "TL"},
  {"name": "Togo", "dial_code": "+228", "code": "TG"},
  {"name": "Tokelau", "dial_code": "+690", "code": "TK"},
  {"name": "Tonga", "dial_code": "+676", "code": "TO"},
  {"name": "Trinidad and Tobago", "dial_code": "+1868", "code": "TT"},
  {"name": "Tunisia", "dial_code": "+216", "code": "TN"},
  {"name": "Turkey", "dial_code": "+90", "code": "TR"},
  {"name": "Turkmenistan", "dial_code": "+993", "code": "TM"},
  {"name": "Turks and Caicos Islands", "dial_code": "+1649", "code": "TC"},
  {"name": "Tuvalu", "dial_code": "+688", "code": "TV"},
  {"name": "Uganda", "dial_code": "+256", "code": "UG"},
  {"name": "Ukraine", "dial_code": "+380", "code": "UA"},
  {"name": "United Arab Emirates", "dial_code": "+971", "code": "AE"},
  {"name": "United Kingdom", "dial_code": "+44", "code": "GB"},
  {"name": "United States", "dial_code": "+1", "code": "US"},
  {"name": "Uruguay", "dial_code": "+598", "code": "UY"},
  {"name": "Uzbekistan", "dial_code": "+998", "code": "UZ"},
  {"name": "Vanuatu", "dial_code": "+678", "code": "VU"},
  {
    "name": "Venezuela, Bolivarian Republic of Venezuela",
    "dial_code": "+58",
    "code": "VE"
  },
  {"name": "Vietnam", "dial_code": "+84", "code": "VN"},
  {"name": "Virgin Islands, British", "dial_code": "+1284", "code": "VG"},
  {"name": "Virgin Islands, U.S.", "dial_code": "+1340", "code": "VI"},
  {"name": "Wallis and Futuna", "dial_code": "+681", "code": "WF"},
  {"name": "Yemen", "dial_code": "+967", "code": "YE"},
  {"name": "Zambia", "dial_code": "+260", "code": "ZM"},
  {"name": "Zimbabwe", "dial_code": "+263", "code": "ZW"}
];
